# -*- coding: utf-8 -*-
"""t-SNE plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nfmxNTLi5Y5Id8kyHgO_E67G7kr8JURM
"""

# Install RDKit
!pip install rdkit-pypi chemplot

import pandas as pd
import matplotlib.pyplot as plt
from rdkit import Chem
from chemplot import Plotter


# Read data
data = pd.read_csv("/content/covid (1).csv") # Replace with your data 


# Create a Plotter object
plotter = Plotter.from_smiles(data["smiles"],target=data["activity"],target_type="C")


# Perform t-SNE dimensionality reduction
plotter.tsne()


# Visualize the t-SNE plot
plotter.visualize_plot()


# Show the plot
plt.show()