# -*- coding: utf-8 -*-
"""Heatplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17DC939dvaUR0FIB-nVgalitA7utAnLUr
"""

!pip install rdkit-pypi

# Commented out IPython magic to ensure Python compatibility.
from rdkit.Chem import AllChem as Chem
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import PandasTools
from rdkit.Chem import Draw
from rdkit import DataStructs

import numpy
import seaborn as sns
import matplotlib

import pandas as pd
# %matplotlib inline

datafile = pd.read_csv('heatplot.csv')
datafile.head(2)

PandasTools.AddMoleculeColumnToFrame(datafile,'smiles', 'Molecule' , includeFingerprints=True)
print([str(x) for x in datafile.columns])

PandasTools.FrameToGridImage(datafile,column= 'Molecule', molsPerRow=4,subImgSize=(150,150))

fplist = [] #fplist
for mol in datafile['Molecule']:
    fp = Chem.GetMorganFingerprintAsBitVect( mol,2 )
    fplist.append(fp)

datafile['mfp2']=fplist

fp1=datafile.at[0,'mfp2']
fp2=datafile.at[1,'mfp2']

from rdkit import DataStructs
DataStructs.TanimotoSimilarity(fp1,fp2)

for r in datafile.index:
    fp1 = datafile.at[r,'mfp2']
    colname = datafile.at[r,'ID']
    simlist = []
    for mol in datafile['Molecule']:
        fp = Chem.GetMorganFingerprintAsBitVect(mol,2)
        sim = DataStructs.TanimotoSimilarity(fp1,fp)
        simlist.append(sim)
    datafile[colname]=simlist

datafile.head(1)

newdatafile = datafile.drop(['smiles',"Molecule",'mfp2'], axis=1)
newdatafile

import seaborn as sns

cm = sns.light_palette("red", as_cmap=True)
s = newdatafile.style.background_gradient(cmap=cm)
s

newdatafile2 = newdatafile.drop(['ID'],axis = 1)

newdatafile2

x_axis_labels = [1,2,3,4,5,6,7,8,9,10] 
y_axis_labels = [1,2,3,4,5,6,7,8,9,10] 

ax = sns.heatmap(newdatafile2, xticklabels=x_axis_labels, yticklabels=y_axis_labels)
plt.xlabel('Compounds')
plt.ylabel('Compounds')
plt.savefig('ax.png')